### ISSUE TITLE
如果想改地区的话应该怎么做呢

### ISSUE THREAD

**Issue by FengYinging** [Baibair/admissionsystem_backend#3]
如果想改地区的话应该怎么做呢，比如说现在要应用到江苏省，那么应该怎么改呢，前端部分我已经导入了jiangsu的json文件，后端部分不知道怎么修改。

**Comment by xhensonli** [comment]
这个已经不是很记得了，我的印象是后端代码没有对省份做特殊处理。
看一下下面这些地方你check一下：
## 1.下载省份的json
一般指定省份后v-chart的地图组件会联网加载json。如果需要断网下使用系统的话就直接F12看请求url，把json下载下来，放到assets/json下。
## 2. 修改地图设置
如果使用下载到本地的json，前端仓库的src/components/backstage/GeoDistribute.vue的guangdongSettings的mapOrigin设置为导入的jiangsu.json，重新命名为jiangsuSettings，并在\<ve-map\>中:settings设置为刚刚的jiangsuSettings。
## 3. 修改请求参数
在前端仓库的src/components/backstage/GeoDistribute.vue下的loadGuangdong方法默认带上的是广东的参数，重新命名为loadJiangsu，request的params.province设置为'江苏'，并在created回调函数中调用loadJiangsu替换掉loadGuangdong。
## 4. 修改excel中的省市数据
修改本仓库的excel/平行志愿考生测试数据.xlsx中的省份和城市，注意列名：1）省份名字不加“省”字，2）城市名字有“市”字。如果省份和城市名还是有误，列名称格式可以参考v-map中的江苏地图，和其保持一致即可。

**Comment by FengYinging** [comment]
好的，我试试
